version: '3.8'
services:
  app:
    build: .
    container_name: nestjs-financial-system
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=testedb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - financial_network

  db:
    image: postgres:latest
    container_name: financial-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testedb  # Alterado para 'testedb'
    ports:
      - '5432:5432'
    networks:
      - financial_network
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: financial-redis
    ports:
      - '6379:6379'
    networks:
      - financial_network

networks:
  financial_network:
    driver: bridge

volumes:
  pg-data:
